package model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="animal")
public class Animal {
private int primary_key;
private String type;
private String image;
private String features;

@DynamoDBHashKey(attributeName="primary_key")
public int getPrimary_key() {
	return primary_key;
}
public void setPrimary_key(int primary_key) {
	this.primary_key = primary_key;
}

@DynamoDBAttribute(attributeName="type")
public String getType() {
	return type;
}
public void setType(String type) {
	this.type = type;
}
@DynamoDBAttribute(attributeName="image")
public String getImage() {
	return image;
}
public void setImage(String image) {
	this.image = image;
}
@DynamoDBAttribute(attributeName="features")
public String getFeatures() {
	return features;
}
public void setFeatures(String features) {
	this.features = features;
}


}
